# Generated by Django 6.0.1 on 2026-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyshot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
