# Generated by Django 6.0.1 on 2026-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyshot', '0002_album_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumb_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
