# Generated by Django 6.0.1 on 2026-02-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partyshot', '0003_photo_s3_key_photo_thumb_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tlink',
        ),
    ]
