# Generated by Django 5.0.6 on 2024-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="location",
            field=models.CharField(default="na", max_length=200),
            preserve_default=False,
        ),
    ]
