# Generated by Django 5.0.6 on 2024-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0002_photo_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="location",
        ),
        migrations.AlterField(
            model_name="party",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="party",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
