# Generated by Django 5.0.6 on 2024-06-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0003_remove_photo_location_alter_party_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="party",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="party.party",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(default="na", max_length=100),
            preserve_default=False,
        ),
    ]
