# Generated by Django 5.0.6 on 2024-06-17 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("party", "0004_tag_party_tag_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="type",
            new_name="key",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="data",
            new_name="value",
        ),
    ]
