# Generated by Django 5.0.6 on 2024-06-25 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shots", "0005_alter_tag_key_alter_tag_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="album",
        ),
    ]
